url: inkoop.github.io

# Site settings
site_title: Inkoop | Web development Consultancy | Ruby on Rails | Nodejs | DevOps | Bangalore
title: Inkoop
email: vivek@inkoop.in
description: "Web development Consultancy based in Bangalore | We work on amazing web technologies like Ruby on Rails, Nodejs, Angular, Backbone."

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/inkoop_in
  - title: facebook
    url: https://facebook.com/inkoop.consultancy
  - title: github
    url: http://github.com/inkoop

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-assets
  # - jekyll-press

# jekyll-press:
#   exclude: 'sitemap.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   js_options: {}      # js minifier options
#   css_options: {}     # css minifier options
#   html_options: {}    # html minifier options

compress_html:
  clippings: all
  comments: all

assets:
  autowrite: true
  cache_type: memory
  cdn: http://da0et0vglk78a.cloudfront.net
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  digest: true
  sources:
    - css
    - images
    - js
    - fonts
  
