url: inkoop.github.io

# Site settings
site_title: Inkoop | Web development Consultancy | Ruby on Rails | Nodejs | Bangalore
title: Inkoop
email: vivek@inkoop.in
description: "Web development Consultancy based in Bangalore | We work on amazing web technologies like Ruby on Rails, Nodejs, Angular, Backbone."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/inkoop_in
  - title: facebook
    url: https://facebook.com/inkoop.consultancy
  - title: github
    url: http://github.com/inkoop

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap

assets:
  cache: true
  